parameter_level: method
version: "3.3"
label: aircraft_2
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  type: default
  MDL: [1]
  QE: 7.5
cost:
  per_site: 200
coverage:
  spatial: 0.9
  temporal: 0.9
t_bw_sites:
  vals: [5]
RS: 4
time: 1
