parameter_level: method
version: "3.3"
label: OGI_QE1
deployment_type: mobile
measurement_scale: component
is_follow_up: False
sensor:
  type: default
  MDL: [0.0362]
  QE: 2.2
cost:
  per_site: 600
coverage:
  spatial: 1
  temporal: 1
t_bw_sites:
  vals: [30]
RS: 2
time: 120
