parameter_level: method
version: "3.3"
label: aircraft_bayes
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  type: default
  MDL: [1]
  QE: 0
  bayes: True
  alpha0: 9.834239406
  alpha1: 1.101077569
  tau: 2.244338669
cost:
  per_site: 200
coverage:
  spatial: 1
  temporal: 1
t_bw_sites:
  vals: [5]
RS: 4
time: 1
