parameter_level: method
version: "3.3"
label: OGI_FU
deployment_type: mobile
measurement_scale: component
is_follow_up: True
sensor:
  type: default
  MDL: [0.0362]
  QE: 0
cost:
  per_site: 700
coverage:
  spatial: 1
  temporal: 1
t_bw_sites:
  vals: [30]
time: 120
