parameter_level: method
version: "3.3"
label: aircraft
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  type: default
  MDL: [1.0]
  QE: 0.0
cost:
  per_site: 200
coverage:
  spatial: 1
  temporal: 1
t_bw_sites:
  vals: [10]
RS: 6
time: 5
n_crews: 1
max_workday: 8
follow_up:
  sort_by_rate: True
  instant_threshold_type: proportion
  interaction_priority: proportion
  proportion: 0.5
