parameter_level: "method"
version: "3.3"
label: "_placeholder_str_"
measurement_scale: "_placeholder_str_" # site/equipment/component
deployment_type: "_placeholder_str_" # mobile/stationary/orbit
sensor:
  type: default # default/OGI_camera_zim(see User manual for MDL values)/OGI_camera_rk
  QE: 0.0
  MDL: [0.01]
  mod_loc: "_placeholder_str_"
bayesian: # parameters if you want to use measured rate based on the bayesian model
  bayes: False # True if you want to use measured rate based on the bayesian model
  measurement_technology: '_placeholder_str_' # should be one of QOGI_A, QOGI_B, QOGI_C, Truck_TDLAS, Aerial_TDLAS, Aerial_NIRHSI
  infer_true: True # True if you want to infer the true rate based on measured rate using bayesian model
  prior: "lognorm" # "lognorm" or "uniform" defining the prior distribution
  prior_params: [1.0,2.6] # shape and scale param for log normal, or the edges of a uniform distribution
  L: 50 # number of leaks to sample from prior
  quantile: 1.0 # if 1.0, then true rate is estimated by the mean of posterior, otherwise, provide quantile as float e.g. 0.025 to use 0.025 quantile from posterior as true rate
  alpha0: 0.0 # default value for coefficients
  alpha1: 0.0
  alpha2: 0.0
  beta0: 0.0
  beta1: 0.0
  gamma: 0.0
  tau: 1.0
  eta: 1.0
coverage:
  spatial: 1.0 # 0.0 to 1.0
  temporal: 1.0 # 0.0 to 1.0
cost:
  per_day: 0
  per_hour: 0
  per_site: 0
  upfront: 0
n_crews: "_placeholder_int_" # whole numbers
consider_daylight: False
RS: "_placeholder_int_"
time: "_placeholder_int_" # minutes
max_workday: 8 # 1 to 23
reporting_delay: 2 # days
t_bw_sites:
  file: "_placeholder_str_"
  vals: [30.0] # minutes
scheduling:
  deployment_months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  deployment_years: ["_placeholder_int_"]
  LDAR_crew_init_location: [-114.062, 51.044]
  home_bases_files: "Airport_AB_Coordinates.csv"
  route_planning: False # True/False
  travel_speeds: ["_placeholder_int_"]
  min_time_bt_surveys: "_placeholder_int_"
weather_envs:
  precip: [0.0, 0.5]
  temp: [-40.0, 40.0]
  wind: [0.0, 10.0]
is_follow_up: False # True/False
follow_up:
  preferred_method: "_placeholder_str_"
  delay: 0 # days
  instant_threshold: "_placeholder_float_" # g/s
  instant_threshold_type: "absolute" # absolute/relative
  interaction_priority: "threshold" # threshold/proportion
  min_followups: ["_placeholder_float_"] # list of values between 0.0 and 1.0
  min_followup_type: "annual" # annual/campaign
  min_followup_days_to_end: 0 # days
  proportion: 1.0 # 0 to 1.0
  redundancy_filter: "recent" # recent/max/average
  sort_by_rate: True # True/False
  threshold: 0.0 # g/s
  threshold_type: "absolute" # absolute/proportion, but setting this to proportion errors out?
