parameter_level: method
version: "3.3"
label: aircraft_s
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  type: satellite
  MDL: [5.79, 1.39]
  QE: 0.0
cost:
  per_site: 200
coverage:
  spatial: 1
  temporal: 1
t_bw_sites:
  vals: [10]
RS: 6
time: 5
n_crews: 1
max_workday: 8
