parameter_level: method
version: "3.3"
label: OGI
deployment_type: mobile
measurement_scale: component
is_follow_up: False
sensor:
  type: default
  MDL: [0.0362]
  QE: 0.0
cost:
  per_site: 600
coverage:
  spatial: 1
  temporal: 1
t_bw_sites:
  vals: [30]
RS: 3
time: 120
