parameter_level: method
version: "3.3"
label: OGI_me
deployment_type: mobile
measurement_scale: component
is_follow_up: False
sensor:
  type: default
  MDL: [0.0362]
  QE: 0.0
bayesian:
  bayes: True
  measurement_technology: QOGI_C
  infer_true: False
  prior: "lognorm"
  prior_params: [1.0,2.6]
  L: 50
  quantile: 1.0
  alpha0: 0.143584345
  alpha1: 0.263838122
  alpha2: 0.766340941
  beta0: 2.040240898
  beta1: 0.230495577
  gamma: 1.885690641
  tau: 0.960453415
  eta: 9.435283625
cost:
  per_site: 600
coverage:
  spatial: 1
  temporal: 1
t_bw_sites:
  vals: [30]
RS: 3
time: 120

